# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MTGqedK7KvnX7fgP9R2EHdWD0XoYi9Gu
"""



import subprocess

url = "https://dapur.bisa.ai/auth.log"
output_file = "auth.log"

try:
    subprocess.run(['wget', url, '-O', output_file, '--no-check-certificate'], check=True)
    print(f"File {output_file} berhasil diunduh")

except subprocess.CalledProcessError as e:
    print(f"Error: {e}")

import re

# Membaca file log dan mengambil IP dari setiap baris
with open('auth.log', 'r') as auth_log:
    lines = auth_log.readlines()

# Pola untuk mencari alamat IP dalam format xxx.xxx.xxx.xxx
ip_pattern = re.compile(r'\b(?:\d{1,3}\.){3}\d{1,3}\b')

# Menggunakan set untuk menyimpan IP unik
unique_ips = set()

# Mendapatkan daftar IP dari file log
for line in lines:
    match = ip_pattern.search(line)
    if match:
        unique_ips.add(match.group())

# Menampilkan IP unik
print("List IP unik:")
for ip in unique_ips:
    print(ip)

# Commented out IPython magic to ensure Python compatibility.
import requests
import json

# %store -r unique_ips # retrieve the stored unique_ips variable

def get_location(ip_address):
    url = f"https://api.ipgeolocation.io/ipgeo?apiKey=012115a2770c495caa762247f523b05b&ip={ip_address}&fields=country_name"
    response = requests.get(url)

    if response.status_code == 200:
      data = json.loads(response.text)
      country_name = data.get("country_name") # use data.get("country_name") to access value
      return country_name
    else:
        return "Lokasi tidak ditemukan"

# Memanggil fungsi untuk mendapatkan informasi lokasi untuk setiap alamat IP
for ip_address in unique_ips:
    location = get_location(ip_address)

    print(f"Alamat IP: {ip_address}, Negara: {location}")

print(!2==2)